[application]
# App (Project) Name
name = "portfolio"

default_platform = "web"

out_dir = "dist"
asset_dir = "assets"

[web.app]
# base_path = "portfolio"

# HTML title tag content
title = "Ajay's Portfolio"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = ["./assets/styling/main.css"]

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[web.watcher]

# When watcher is triggered, regenerate the `index.html`
reload_html = true

# Which files or dirs will be monitored
watch_path = ["src", "public"]
